---
- name: Test SSH connectivity to all Windows and Linux hosts
  hosts: targets
  gather_facts: false
  tasks:
    - name: Run 'whoami' to verify SSH connection
      shell: whoami
      register: result

    - name: Show connection result
      debug:
        msg: "Successfully connected to {{ inventory_hostname }} as {{ result.stdout }}"
